name: "Download Release"
description: "Download GitHub release file in a repo"
inputs:
  repo:
    description: "Name of the repository"
    required: false
    default: ${{ github.repository }}
  file:
    description: "The file to be downloaded"
    required: true
  version:
    description: "The version of the release"
    required: false
    default: "latest"
  out:
    description: "The path to the output file"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - run: >
        pwsh ${{ github.action_path }}/download.ps1 
        -Repository ${{ inputs.repo }}
        -File ${{ inputs.file }}
        -Version ${{ inputs.version }}
        -OutPath ${{ inputs.out }}
      shell: pwsh
